default-resources: [mem_free=1]

software:
        create_index: ../bin/create_fastq_indexdb.py
        contfree_ngs: ../bin/ContFree-NGS.py
        jq: ../bin/jq-linux64
        extract_contigs: ../bin/extractSequencesWithMinLength.pl
        fastq-dump: /Storage/data1/felipe.peres/src/sratoolkit.3.0.10-ubuntu64/bin/fastq-dump
        fastqc: /Storage/progs/FastQC/fastqc
        bbduk: /Storage/progs/bbmap_35.85/bbduk2.sh
        kraken2: /Storage/progs/miniconda2/bin/kraken2
        trinity: /Storage/progs/trinityrnaseq-Trinity-v2.8.5/Trinity
        cd_hit_est: /Storage/progs/cd-hit-v4.8.1-2019-0228/cd-hit-est
        transrate: /Storage/progs/transrate-1.0.3-linux-x86_64/transrate
        salmon: /Storage/progs/salmon-1.3.0_linux_x86_64/bin/salmon
        ffq: ~/.conda/envs/snakemake-tutorial/envs/snakemake_conekt/bin/ffq
